#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Geovanny Alzate Sandoval
title: El Vany dev
comments: true

# Short bio or description (displayed in the header)
description: I'm passionate to software development and new technologies, methodologies and everything about design and software architecture, I have 10 years’ experience into this passionate world where I have worked like developer, technical leader and software architect. So I just want to share my experience and of course learn more, because teaching is the best way to learn!. Here you can find stuff like Asp.Net MVC, Asp.Net Web Api, Web services, Entity Framewor, Angularjs, Web Technologies, Cloud, Azure and more...Focused on Microsoft Technologies

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/vany0114/vany0114.github.io/master/images/avatar.jpg

#
# Flags below are optional

social:
   github: vany0114
   twitter:
   facebook:
   email: elvany0114@gmail.com
   linkedin: geovannyalzatesandoval

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus_shortname: elvanydev

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-96927545-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://vany0114.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: "blog/page:num/"

# The release of Jekyll Now that you're using
version: v1.2.0

markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge

#highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
